name: webthree
description: WebThree - a web3 library for dart for interaction with ethereum nodes using HTTP or WebSocket. Supports custom credentials providers like WalletConnect and Metamask.
version: 2.5.5+2
homepage: https://devopsdao.com
repository: https://github.com/devopsdao/webthree

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.3.1
  build_config: ^1.1.0
  built_collection: ^5.1.1
  code_builder: ^4.3.0
  collection: ^1.16.0
  convert: ^3.0.2
  dart_style: ^2.2.4
  http: ^0.13.5
  js: ^0.6.4
  json_rpc_2: ^3.0.2
  meta: ^1.8.0
  path: ^1.8.2
  pointycastle: ^3.6.2
  stream_channel: ^2.1.0
  stream_transform: ^2.0.1
  typed_data: ^1.3.1
  universal_html: ^2.0.8
  uuid: ^3.0.6

dev_dependencies:
  async: ^2.9.0
  build_runner: ^2.2.1
  build_test: ^2.1.5
  coverage: ^1.6.1
  test: ^1.21.6
  web_socket_channel: ^2.2.0
