name: webthree
description: WebThree - a web3 library for dart for interaction with ethereum
  nodes using HTTP or WebSocket. Supports custom credentials providers like
  WalletConnect and Metamask.
version: 2.7.1
homepage: https://docs.dodao.dev
repository: https://github.com/devopsdao/webthree

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.1
  build_config: ^1.1.1
  built_collection: ^5.1.1
  code_builder: ^4.5.0
  collection: ^1.16.0
  convert: ^3.1.1
  dart_style: ^2.3.2
  http: ^1.0.0
  js: ^0.6.7
  json_rpc_2: ^3.0.2
  meta: ^1.9.1
  path: ^1.8.3
  pointycastle: ^3.7.3
  stream_channel: ^2.1.1
  stream_transform: ^2.1.0
  typed_data: ^1.3.2
  universal_html: ^2.2.3
  uuid: ^4.1.0

dev_dependencies:
  async: ^2.11.0
  build_runner: ^2.4.6
  build_test: ^2.2.0
  coverage: ^1.6.3
  test: ^1.24.6
  web_socket_channel: ^2.4.0
  expector: ^0.1.2
  intl: ^0.18.0
  lints: ^2.0.0